### PR TITLE
SASS support

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**
compiling sass to CSS before webpack build

### CODE REVIEW

**Comment by gdi2290** [comment]
nice, can you update package.json?

**Comment by kuldeepkeshwar** [comment]
updated pr

**Comment by kuldeepkeshwar** [comment]
@gdi2290 please merge the PR or if there is anything which needs to be changed ,please let me know

**Comment by kuldeepkeshwar** [comment]
removed conflicts in package.json

**Comment by samvloeberghs** [comment]
let's merge this please? :)

**Comment by debanjanbasu** [comment]
Please, this is an essential feature, and needs to be merged ASAP.

**Comment by flauc** [comment]
Wouldn't it be better to make this a separate branch? I think the starter should leave the choice of css pre processor to the developer.

**Comment by samvloeberghs** [comment]
@flauc, who still wants to use CSS instead of SCSS these days..? Think about it

**Comment by flauc** [comment]
@samvloeberghs Yes but sass is far from the only choice CSSNext is getting pretty popular for example, then you have less, stylus...

**Comment by samvloeberghs** [comment]
@flauc whatever you use, you will have to compile it before you can use it in AOT..
So don't care if it's sass, CSSNext or less. An example would be nice :)

**Comment by debanjanbasu** [comment]
Yes Indeed, actually the solution by @kuldeepkeshwar is also somewhat not perfect. The sass has to be manually compiled eveytime. Not at all ideal. Ideally there should be a watcher doing this.

**Comment by kuldeepkeshwar** [comment]
@debanjanbasu I think you are right, right now it will work for the production build only, I'll add watcher for the sass to make it developer friendly

**Comment by debanjanbasu** [comment]
Yes indeed, that will make it really developer friendly.

**Comment by joaogarin** [comment]
Isn't using @ngtools/webpack a simpler solution for making scss files compatible with AOT?

**Comment by JozefFlakus** [comment]
@joaogarin true, @ngtools/webpack integrates nicely with webpack sass loaders

**Comment by gdi2290** [comment]
can you update with @ngtools/webpack or https://github.com/shlomiassaf/ngc-webpack

**Comment by ampgular** [comment]
@gdi2290 @FrozenPandaz I am currently learning webpack and I think I coould take over this PR including in the new Unicersal-starter the possibility lto load css and sass, whar do you think?

**Comment by m98** [comment]
Pull request #418  will close this issue, Angular CLI configs support CSS processors.

**Comment by Toxicable** [comment]
I think this PR is no longer needed since the CLI can handle SASS which we have a example for now

**Comment by m98** [comment]
@gdi2290 Now I think it should not be closed because we still have both custom-webpack and the CLI version on universal-starter.
This can be helpful for users who are going to use universal-starter custom-webpack

**Pull request closed without merging**
