### PR TITLE
include WebWorker support client-side

### PR DESCRIPTION
**Pull request by gdi2290**
(work in progress)

### CODE REVIEW

**Comment by gdi2290** [comment]
yo @jteplitz602 can you help me with adding webworker (webpack support) support to the starter?

**Comment by gdi2290** [comment]
we got webworkers working on the `angular2-webpack-starter` will update the repo after improved developer experience

**Comment by swirlycheetah** [comment]
Sorry, misclick! Sounds good :+1:

**Comment by gdi2290** [comment]
np

**Pull request closed without merging**
