### PR TITLE
Webpack settings: ability to use external templates and scss, prod task

### PR DESCRIPTION
**Pull request by logvinoleg89**
Webpack settings: ability to use external templates and scss
To add external templates or css use this in Component decorator  

`....
styles: [require('./app.component.scss')],
template: require('./app.component.html')
....`

Webpack settings: prod task
Use this to build minified production version of app in /dist
`ENV=prod npm start`

### CODE REVIEW

**Comment by logvinoleg89** [comment]
I signed it!

**Comment by sabbirrahman** [comment]
@logvinoleg89  Hello, Nice work. I see you have added sass support here. If you have some time can you add less support? Or help me with this problem #132?

**Comment by Hongbo-Miao** [comment]
Developers should have freedom choosing sass or less, or neither of them.

And to make sass work, actually only need two packages:
node-sass, sass-loader

**Comment by gdi2290** [comment]
currently AoT has problems with scss so we can't even merge this if we wanted to. I also would leave the opinion to for their css processor to the developer (even though scss is the most popular one).

**Pull request closed without merging**
