### PR TITLE
Webpack to Browserify

### PR DESCRIPTION
**Pull request by tamascsaba**
Use browserify-middleware:
* Faster compile and watch
* Better environments support
* Automatically rebuilds whenever files change in development
* Minification automatically enabled for production
* gzip automatically enabled for production
* etags for caching automatically enabled for production

### CODE REVIEW

**Comment by tamascsaba** [comment]
First commit is extend webpack functionality, but I realized browserify is much better then webpack.

**Comment by tamascsaba** [comment]
It is a good example:
Webpack watch: 1.21s
Browserify watch: 0.32s

**Comment by tamascsaba** [comment]
Can i make separate P.R. with only add browserify?

**Comment by gdi2290** [comment]
@tamascsaba I'm trying to keep the Webpack workflow. This change doesn't fix another problem which is watching and compiling the server version of the component (currently handled by `ts-node` on bootstrap)

**Comment by tamascsaba** [comment]
Thanks for the answer.

**Pull request closed without merging**
