### PR TITLE
Brotli Compression support

### PR DESCRIPTION
**Pull request by gouravcoder**
Brotli compression support:

main.bundle.js:
```
without compression = 603kb
with compression()/gzip: 144kb = 24%, total size reduction - 76%
with brotli: 113kb = 19%, total size reduction - 81%
```

### CODE REVIEW

**Comment by gdi2290** [comment]
thanks!

**Comment by ocombe** [comment]
Yeah that's cool, but now it doesn't work on windows :(
I haven't been able to build the project because brotli won't install on windows for some reasons.
I've revert these changes and now I can run the project.

**Comment by gouravcoder** [comment]
@ocombe I use windows too, it is working on my machine, have you tried deleting node_modules folder and reinstalling...

**Comment by ocombe** [comment]
yes, I've tried a lot of things. Now that I think about it, maybe the problem is that I use node 7.x and there are no binaries for this version

**Comment by gouravcoder** [comment]
well i have node 7.2.0 & npm 3.10.9
windows 10.

**Comment by gdi2290** [comment]
it's probably best to revert it and create a wiki page to talk about changing it to brotli

**Comment by gdi2290** [comment]
@gouravcoder can you make a PR to revert it and update the readme?

**Comment by ocombe** [comment]
if it's just me it's not necessary

**Comment by gouravcoder** [comment]
@gdi2290 updated pr

**Pull request merged**
