### PR TITLE
Fix typo in README.md (stylesUrl instead of styleUrls) 

### PR DESCRIPTION
**Pull request by pbellon**
README mention `stylesUrl` instead of `styleUrls` which can create confusion.

### CODE REVIEW

**Comment by MarkPieszak** [comment]
Good catch!! Always put that `s` in the wrong spot. 
Can you fix the conflicts and we can add it in?

**Comment by gdi2290** [comment]
@pbellon can you update your PR so I can merge it?

**Comment by pbellon** [comment]
I will today

**Comment by pbellon** [comment]
Okay I've managed to resolve the conflicts, it should be ok now.

**Pull request merged**
