### PR TITLE
chore(package): Update dependencies

### PR DESCRIPTION
**Pull request by MarkPieszak**
router / etc

### CODE REVIEW

**Comment by Hongbo-Miao** [comment]
@MarkPieszak Hi, you need add another change
for the file **src/app/app.routes.ts**
Change from
`{ path: '', redirectTo: 'home'},`
to
`{ path: '', redirectTo: 'home', terminal: 'true' },`
to make it work after updating to latest router.

Otherwise, you will get the error:

> index.js:41394 EXCEPTION: Error during instantiation of Router!.

**Comment by Hongbo-Miao** [comment]
Hi, @MarkPieszak, you need add another change
for the file **src/app/app.routes.ts**

Change from
`{ path: '', redirectTo: 'home' },`
to
`{ path: '', component: 'home' },`
to make it work after updating to latest router.

Otherwise, you will get the error:

> index.js:41394 EXCEPTION: Error during instantiation of Router!.
> index.js:41394 ORIGINAL EXCEPTION: Error: Invalid route configuration of route '{path: "", redirectTo: "home"}': please provide 'pathMatch'. The default value of 'pathMatch' is 'prefix', but often the intent is to use 'full'.

**Comment by manekinekko** [comment]
@MarkPieszak @Hongbo-Miao this is the new syntaxe when using `redirectTo`:

```
{ path: '', redirectTo: 'home', pathMatch: 'full' }, // <-- see docs for that
```

**Comment by Hongbo-Miao** [comment]
@manekinekko Hi, that is what I did before, once I added `pathMatch: 'full'`, I got another error:

```
    ERROR in ./src/app/app.routes.ts
    (6,35): error TS2322: Type '({ path: string; redirectTo: string; pathMatch: string; } | { path: string; component: typeof Hom...' is not assignable to type 'Route[]'.
      Type '{ path: string; redirectTo: string; pathMatch: string; } | { path: string; component: typeof Home...' is not assignable to type 'Route'.
        Type '{ path: string; redirectTo: string; pathMatch: string; }' is not assignable to type 'Route'.
          Object literal may only specify known properties, and 'pathMatch' does not exist in type 'Route'.
```
I guess still need some typings issues need to be fixed.

**Comment by MarkPieszak** [comment]
Ah shoot meant to add that, forgot! Apologies thanks for noticing guys I'll update ! 🙈

**Comment by gdi2290** [comment]
LGTM after fix

**Comment by Hongbo-Miao** [comment]
The latest starter uses "typescript": "^2.0.0-beta", so this PR need other improvement.

**Comment by MarkPieszak** [comment]
Got latest and fixed merge issues & added the missing `patchMatch` for the router.

**Pull request merged**
