### PR TITLE
Update version numbers for some dependencies

### PR DESCRIPTION
**Pull request by SystemDisc**
need to update angular to 2.2.3 and zone to 0.7.4 to play well with other npm packages

See https://github.com/mysqljs/mysql/pull/1614

### CODE REVIEW

**Comment by SystemDisc** [comment]
I signed it!

**Comment by Koslun** [comment]
@SystemDisc There was an explicit revert back to ~2.1.2 in this commit: https://github.com/angular/universal-starter/commit/15c7017b82b2d5dbb2d450bd506ccb34cd5d9ecb

Believe @gdi2290 mentions the reason himself somewhere in this repo but not sure where. Regardless I believe it was due to angular universal itself depends on various private imports from Angular that change further in 2.2 and likely beyond. Had it working reasonably well myself using 2.2, though no AoT. Depending on what parts of Angular you use it might however not be a good idea I reckon.

Think the best course for this repo is to wait for Angular Universal to be integrated into the official Angular repo. After which it will begin properly following the regular Angular releases.

You might want to experiment with 2.2.x yourself either way though.

**Comment by SystemDisc** [comment]
Oh, ok. Thanks for the info. Is there any word on when Angular Universal might become part of the official repo? The dependency on a buggy Zone.js is a bit silly

**Comment by gdi2290** [comment]
universal will be merged into core as @angular/platform-universal during 4.x.x release in the meantime there will be a 2.4 release for angular2-universal that will update everything

**Comment by SystemDisc** [comment]
@gdi2290, is there an ETA on the 2.4 release of angular2-universal?

**Pull request closed without merging**
