### PR TITLE
Added route example

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**

### CODE REVIEW

**Comment by gdi2290** [comment]
@kuldeepkeshwar can you rebase?

**Comment by kuldeepkeshwar** [comment]
yes

**Comment by kuldeepkeshwar** [comment]
I signed it!

**Comment by gdi2290** [comment]
@kuldeepkeshwar sorry again can you rebase and add me to your forked repo that way I can update your PR in the future

**Comment by kuldeepkeshwar** [comment]
@gdi2290 updated the PR and added you to the forked repo

**Comment by gdi2290** [comment]
thanks!

**Comment by Hongbo-Miao** [comment]
This PR causes two Home components, https://github.com/angular/universal-starter/blob/c43d81dabf5b16620f2a2a250b5711ec2e016378/src/app/app.routes.ts#L2toL5

**Comment by Hongbo-Miao** [comment]
And if you seperate module in Home and About, [app.routes.ts](https://github.com/angular/universal-starter/blob/master/src/app/app.routes.ts) should also change.

**Comment by antonyRoberts** [comment]
@kuldeepkeshwar Have you had any luck with lazy loaded routes. I notice this PR does not use them at all

**Comment by kuldeepkeshwar** [comment]
@antonyRoberts yes I got it working and will creating another PR for this by tomorrow evening

**Comment by antonyRoberts** [comment]
@kuldeepkeshwar Cool good to hear, looking forward to seeing it

**Comment by kuldeepkeshwar** [comment]
@antonyRoberts added lazy routing 
https://github.com/angular/universal-starter/pull/235
https://github.com/kuldeepkeshwar/universal-starter

**Comment by Hongbo-Miao** [comment]
@kuldeepkeshwar can u fork the latest commit and create a PR based on it?

**Comment by kuldeepkeshwar** [comment]
@Hongbo-Miao done

**Pull request merged**
