### PR TITLE
Test infrastructure and SSR Compression Added

### PR DESCRIPTION
**Pull request by tsukhu**
* Added missing support for tests - Karma / Jasmine / Protractor - for both unit and e2e tests
* Also added support for compression in the SSR mode

### CODE REVIEW

**Comment by tsukhu** [comment]
I signed it!

**Comment by Toxicable** [comment]
I don't think either of these features are needed.
This repo is to show how you can use Universal with the Angular CLI not how to do unit/e2e testing with Angular, while I think these are important I don't think they warrant the extra complexity for showing a bare bones of what an Angular Universal project would look like.

As for compression, this should be handled by your Reverse proxy such as nginx or IIS not your node app

**Comment by tsukhu** [comment]
@Toxicable - Thank you for your comment. I totally understand where you are coming from and it is entirely up to your discretion . 
My POV of this PR was 1) Any one wanting to use this in a ci/cd environment will require the basic test infrastructure to be in place 2) The compression for the express server is more for the point of view of someone wanting to test out the performance locally , would require some kind of compression to see the difference of ssr

**Comment by Toxicable** [comment]
Closing for the above reasons

**Pull request closed without merging**
