### PR TITLE
Systemjs update from master

### PR DESCRIPTION
**Pull request by bjwyse**
To ensure that the SystemJS build closely resembles the Webpack build, I took the latest master branch and made it build with SystemJS rather than take the current systemjs branch and try to update everything.

Builds and runs but I had to comment out angular2-universal-preview/polyfills in client.ts. I was getting some errors when this was added.

### CODE REVIEW

**Comment by bjwyse** [comment]
Confirm I authored the commits but used wrong email for one commit.

**Comment by gdi2290** [comment]
it looks like you had an old fork because you have a merge commit rather than using rebase

**Comment by gdi2290** [comment]
te changes are great though

**Comment by bjwyse** [comment]
Let me sort that and open a new PR.

**Comment by gdi2290** [comment]
@bjwyse thanks!

**Pull request closed without merging**
