### PR TITLE
lint(prerender.ts):  Forbidden 'var' keyword, use 'const' instead

### PR DESCRIPTION
**Pull request by philip-firstorder**
Missing whitespaces

Tested with https://www.codefactor.io/

### CODE REVIEW

**Comment by philip-firstorder** [comment]
I signed it!

**Comment by CaerusKaru** [comment]
We can't merge this until you sort out the CLA issue; please make sure your commit email is the same as the one you use to sign the CLA.

**Comment by philip-firstorder** [comment]
I signed it!

**Comment by philip-firstorder** [comment]
I signed it!

**Pull request merged**
